### PR TITLE
SMT stencils

### PR DESCRIPTION
**Pull request by mathewlippincott**
added board stencils for surface mount solder application

### CODE REVIEW

**Comment by fr293** [comment]
Ah, those are much more useful than the Gerbers, how did you produce them? I know a couple of techniques, but they're a bit hit and miss, if I'm honest!

**Comment by fr293** [comment]
One slight note to make is that Rev F suffers from the little problem of refusing to communicate to more than four boards or so, the circuit that activates the level shifting chip isn't very well designed, so I fixed that in Rev G.

**Comment by mathewlippincott** [comment]
Making stencils:
I produced the file through Eagle-- I went to View-> layer settings and told it to only display only 'tCream' (the solder pads) and 'Dimension' (the board outline).  I then printed those as a PDF (a default function on Mac) and converted that file to an SVG through Adobe Illustrator, but it could have been done through Inkscape as well.

**Comment by mathewlippincott** [comment]
I figured RevG was just production file for the Rev F CAD files in the repository. I'm not familiar with working directly with Gerber files, I generate them to send to fabs but I've never used them.  Is there a way to get a parts list/circuit diagram out of the file?   Could you upload the EagleCAD for RevG?

I'm not quite understanding the problem you're describing with RevF.  I'm using one Pi B+ and one RevF board.  Will I encounter some communication issue?

**Comment by fr293** [comment]
The zip folder (RevG.zip) contains all the files for G, which is now the preferred version for general use. 

F suffers from a problem when more than three boards are connected in series, so you shouldn’t have any problems running a single one. It also has one mistake in the wiring, meaning that the activity lights (the red and green LEDs) for the Z axis are connected to the opposite pins, compared to X and Y. This is fixed in G. 

I’ve also just noticed that there might be an element of confusion related to the naming convention here. The code is often called things like StepperF, which is not to say that it belongs to revision F, it’s just that my name is Fergus and I wanted a quick way to differentiate between the normal stepper library and mine! 

Yours truly,

Fergus Riche 
Magdalene College
Cambridge
Mobile: +447974304049

**Comment by mathewlippincott** [comment]
Hah! yes, Stepper F is Fergus's Stepper. I'll remember.

Great to hear that I won't likely encounter communications problems with RevF.

The RegG zip file doesn't have CAD files in it, it only contains Gerber files:
schematicmrpRevG.GBL
schematicmrpRevG.GBS
schematicmrpRevG.GTL
schematicmrpRevG.GTO
schematicmrpRevG.GTS
schematicmrpRevG.TXT

**Comment by fr293** [comment]
I’ve added the schematics now, thanks for pointing that out. I’d like to tidy it all up a bit, but a new revision will be coming out before Christmas, which will make the previous designs redundant! 

Yours truly,

Fergus Riche 
Magdalene College
Cambridge
Mobile: +447974304049

**Pull request merged**
